import "ARTContainer.idl";

namespace ART{
    [default_interface]
    runtimeclass ARTSurfaceView : Windows.UI.Xaml.Controls.Grid, ARTContainer {
        ARTSurfaceView(Microsoft.ReactNative.IReactContext context);
    };
}
